### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#113]
Considering GraalVM

**Comment by piiertho** [comment]
We should keep looking https://github.com/oracle/graal/issues/373 
Hope it will be supported soon.

**Comment by LifeIsStrange** [comment]
If I understand correctly GraalVM for IOS is supposed to work already if you use latest version.
It seems using the gluonhq is [not necessary](https://github.com/gluonhq/substrate/issues/1117) although it could still be useful if e.g. you need shared library support ?
https://github.com/gluonhq/substrate/commit/a1a6a37826bd5139b0905064d436d7b07da1ccbb

Good luck, this might "just work" :)

**Comment by piiertho** [comment]
In fact we don’t need gluon at all even if we need shared library support. Everything is there in graal vm.  
What we need is cap files from gluon, and reproduce native image call made in there maven plugin in our graalvm plugin. And then add same options they add to Xcode project in godot exported project.  
Also we maybe need c files included in gluon repo.  
To be honest I hope graal will fully support iOS in a near future to simplify this…
