### ISSUE TITLE
Stackoverflow on CI

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#140]
We get the following stackoverflow issue on CI from time to time:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':godot-library:generateAPI'.
> java.lang.StackOverflowError (no error message)
```
Most of the time a rerun is enough and it runs through but definitely something we need to fix.

**Comment by CedNaru** [comment]
It's likely due to when we recursively call the parent of a class or another.
Will probably be fixed with a good tailrec.
