### ISSUE TITLE
Project as gradle module does not work

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#148]
Currently it is not possible to include a godot kotlin project in a gradle multi module project.
Here is a project structure to illustrate:
![image](https://user-images.githubusercontent.com/48322356/115119788-79b39100-9faa-11eb-8f5a-92d9ec63bae7.png)
Gradle command cannot be run from editor because we're looking for gradlew from `res` path root.
Also, build command is hardcoded.
See `BuildManager::build_blocking`

**Comment by raniejade** [comment]
Can you give more details about the structure? i.e what module is the godot project. Also can you explain what you are trying to achieve?

**Comment by chippmann** [comment]
I suspect you mean building from withing the godot editor with our godot editor plugin.
Yeah when developing that i didn't think of the case that the godot project might be just a module inside a gradle project.

But I'm unsure how to solve this. I guess the easiest way would just be to let the user define the path to the gradlew in a setting.
So it can be set manually if the godot project is not the root gradle project and hence does not include a gradle wrapper.

**Comment by sirnuke** [comment]
Simply adding an additional wrapper to the Godot project module (gradlew*, gradle/wrapper/gradle-wrapper.*) seems to work without issue.  Allowing the gradlew location to be specified would be a better fix.

The usecase for myself is I wrote a simple SLF4J -> GD.Print/GD.PrintErr logger and wanted one module to contain the library and the other to be an example project for testing.

**Comment by chippmann** [comment]
Yeah i see.
For now you could also just build from the IDE or CLI to not have the need to add an additional gradle wrapper just for building from withing the editor.
That said I'll fix this for the `0.1.4` release by adding said option to the editor settings.
