### ISSUE TITLE
Auto reloading not working

### ISSUE THREAD

**Issue by raniejade** [utopia-rise/godot-kotlin-jvm#149]
I've tried adding a new property to a script then triggered a gradle build. However, the editor doesn't seem to pick up the new property. Had to restart the editor for the new property to show up. Tried it on windows, not sure if auto reloading works on other OS.

**Comment by piiertho** [comment]
Hey !
Did you try to close scene and reopen it ?

**Comment by raniejade** [comment]
Yep and it didn't work.

**Comment by chippmann** [comment]
Indeed. Just tested it on linux as well. I guess we've broken the reloading somehow.

**Comment by chippmann** [comment]
Found the issue. The build lock dir created by the gradle plugin is not the same as the one we're looking for in the `Bootstrap` class. Reason being; we're not passing in the project root dir anymore, we're passing in the libs dir.
Should be easy to fix
