### ISSUE TITLE
Make defaultValues in entry file a true provider

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#151]
Replace the current `by lazy` impl with a true provider.

Current: 
```kotlin
open val registerObjectNullablePreInitDefaultValue: OtherScript by lazy { OtherScript() }
```
goal:
```kotlin
open val registerObjectNullablePreInitDefaultValue: () -> OtherScript = { OtherScript() }
```

**Comment by chippmann** [comment]
@CedNaru I just thought about something. Isn't the editor checking resource default value's by pointer?
so if we do a true provider, the pointer to the object would not be the same, hence for the editor the values would not be the same even though they are.
Wasn't this the reason why we implemented it as values stored in entry in the first place?

**Comment by CedNaru** [comment]
But you would need a default value per instance of script, not globally.
Otherwise, all the scripts would share the same instance
