### ISSUE TITLE
Document default value behaviour

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#162]
The default value behavior should be documented in the knowledge base
![1](https://user-images.githubusercontent.com/22662033/115375080-ba3f2480-a1cd-11eb-8898-e3b5595eb425.png)

**Comment by CedNaru** [comment]
Closing as it's obsolete, default values are no longer registered, instead Godot load every script once to get their runtime default values directly. This behavior mimic how default values are obtained for regular classes and extensions.
