### ISSUE TITLE
Editor bugs: Grid is missing, incorrect line numbers in scripts

### ISSUE THREAD

**Issue by Sipaha** [utopia-rise/godot-kotlin-jvm#166]
Version: https://github.com/utopia-rise/godot-kotlin-jvm/releases/tag/0.1.4-3.2.3
Platform: Ubuntu 20.04.2 LTS
Editor: godot-kotlin-jvm_editor_x11_.zip

First, I want to say that your project is amazing. I really love Kotlin and the ability to use this language in Godot makes me very happy!

I am trying to work with your build of godot editor and encountering several problems: 

1. Editor grid is missing:
![image](https://user-images.githubusercontent.com/3995047/115548995-4f2b4600-a2d2-11eb-82f5-a6b709bc122d.png)

2. Incorrect line numbers in all scripts (include GDScript):
![image](https://user-images.githubusercontent.com/3995047/115549055-666a3380-a2d2-11eb-9ae3-2517fb336c2c.png)

3. Remote tree of running game also doesn't work. Maybe this log will help:

`
Running: /home/sipaha/Programs/godot/godot.x11.opt.tools.64 --path /home/sipaha/GodotProject --remote-debug 127.0.0.1:6007,000000 --allow_focus_steal_pid 157961 --position 448,240 res://Spatial.tscn
ERROR: to_int: Cannot represent 6007,000000 as integer, provided value is too big.
   At: core/ustring.cpp:1794.
ERROR: connect_to_host: Remote Debugger: Unable to connect. Status: 3.
   At: scene/debugger/script_debugger_remote.cpp:95.
`

I am checked this builds:
1. last release (godot-kotlin-jvm/releases/tag/0.1.4-3.2.3) - problems exist
2. build from sources with kotlin module - problems exists
3. build from same engine sources, but without kotlin module - problems doesn't exists
4. last official release - problems doesn't exists

**Comment by chippmann** [comment]
Hi @Sipaha 
Interresting. None of us has any of the issues you show here (on none of the 3 OS).
As you running a 32bit OS?

**Comment by Sipaha** [comment]
Hi @chippmann 

> Are you running a 32bit OS?

No, this is my system info from `inxi -F`:

![image](https://user-images.githubusercontent.com/3995047/115554286-813fa680-a2d8-11eb-8262-c78677c794bd.png)

**Comment by chippmann** [comment]
Thx a lot.
These issues are indeed interresting. I'm in the process of setting up a ubuntu vm to check if we have those issues on ubuntu only. Personally I'm on arch and don't experience those issues.
I'll update the issue once i gained some insights.

**Comment by chippmann** [comment]
I sadly cannot reproduce the issue you're having on the VM either. It's using the same versions as you as far as i can see:
```
System:    Host: godotTestVm Kernel: 5.8.0-50-generic x86_64 bits: 64 Desktop: Gnome 3.36.7 
           Distro: Ubuntu 20.04.2 LTS (Focal Fossa)
```
Hard to tell what the issue might be.
I can't think of something in our module which could cause those issues to happen. Especially that one with the grid. We don't touch that part of the editor.
Also it seems that all ints are handled as floats somehow. Given the output here: `--remote-debug 127.0.0.1:6007,000000`. The port clearly should be an int. Also the line numbers are rendered as floats rather than int's which is very weird.

Are you trying to compile with a "clean" godot engine code base or did you do some previous modifications to it before adding our module?

**Comment by raniejade** [comment]
Might be good to download and test out the official Godot build and see if the same issue happens. If so, then it might be a Godot problem.

**Comment by chippmann** [comment]
> Might be good to download and test out the official Godot build and see if the same issue happens. If so, then it might be a Godot problem.

According to the issue this already was tested

**Comment by raniejade** [comment]
Ohh interesting. Hmmm, I wonder if something is wrong with the way we build the engine. Have you looked at the libraries it is looking for (ldd <exec>)?

**Comment by chippmann** [comment]
> Ohh interesting. Hmmm, I wonder if something is wrong with the way we build the engine. Have you looked at the libraries it is looking for (ldd )?

Yeah hard to tell. @CedNaru and I looked at the [github workflow](https://github.com/godotengine/godot/blob/master/.github/workflows/linux_builds.yml) of the Godot engine and couldn't find any difference to what we build.
@Sipaha Could you try what @raniejade suggested? Makes no sense if i try when i cannot reproduce it.

**Comment by Sipaha** [comment]
I found that problem appear after this line of code is executed in GDKotlin::init method (everything after this line is commented):

![image](https://user-images.githubusercontent.com/3995047/115647658-67d94180-a34e-11eb-9f30-7d1d9a50b94c.png)

If I remove this line everything become fine (at least grid and line numbers in scripts displayed as expected).

Maybe it depends on JDK version? I have tried with 11 and 15, but nothing changed.

I will continue to search source of problem later.

**Comment by Frontrider** [comment]
> Thx a lot.
> These issues are indeed interresting. I'm in the process of setting up a ubuntu vm to check if we have those issues on ubuntu only. Personally I'm on arch and don't experience those issues.
> I'll update the issue once i gained some insights.

I have this issue on manjaro.

**Comment by chippmann** [comment]
@Frontrider Now it get's really interresting. I'm running Manjaro as well. 
What jdk version do you have?

**Comment by Frontrider** [comment]
I added java 11 to it.

**Comment by chippmann** [comment]
Hmm same as me. Oracle or OpenJdk?

**Comment by Frontrider** [comment]
openjdk, also checked the line numbers and yes, they are floats.

**Comment by piiertho** [comment]
Ok got the same on apple silicon.
If you run in verbose mode from terminal, do you have this printed ?
```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
ERROR: poll: /Users/pierre-thomasmeisels/Library/Application Support/Godot/editor_settings-3.tres:9 - Parse Error: Expected 4 arguments for constructor
   At: scene/resources/resource_format_text.cpp:592.
ERROR: load: Failed to load resource '/Users/pierre-thomasmeisels/Library/Application Support/Godot/editor_settings-3.tres'.
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Failed loading resource: /Users/pierre-thomasmeisels/Library/Application Support/Godot/editor_settings-3.tres. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:279.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:938.
ERROR: _display_error_with_code: SceneShaderGLES3: Vertex Program Compilation Failed:
ERROR: 0:470: Too many arguments to constructor of 'vec3'
ERROR: 0:470: Too many arguments to constructor of 'vec3'
ERROR: 0:470: Too many arguments to constructor of 'vec3'
```

**Comment by piiertho** [comment]
So I found the line that cause the bug:
Here is my local version of `Jvm::create`:
```cpp
    JavaVM* Jvm::create(const InitArgs& initArgs) {
        size_t nOptions { initArgs.options.size() };
        auto *options = new JavaVMOption[nOptions];
        JavaVMInitArgs args;
        args.version = initArgs.version;
        args.nOptions = nOptions;
        args.options = options;

        for (auto i = 0; i < nOptions; i++) {
            args.options[i].optionString = (char*) initArgs.options[i].c_str();
        }

        JavaVM* java_vm{nullptr};
        JNIEnv* jni_env{nullptr};
        jni::CreateJavaVM create_java_vm{JvmLoader::get_create_jvm_function()};
        jint result{create_java_vm(&java_vm, reinterpret_cast<void**>(&jni_env), &args)};
        
        delete[] options;
        JVM_CRASH_COND_MSG(result != JNI_OK, "Failed to create a new java_vm!")
        return java_vm;
    }
```


This line seems to be responsible:
```cpp
jint result{create_java_vm(&java_vm, reinterpret_cast<void**>(&jni_env), &args)};
```

So it seems to be when calling `JNI_CreateJavaVM` we get back from jvm dyn lib loaded at runtime.

**Comment by Sipaha** [comment]
> Ok got the same on apple silicon.
> If you run in verbose mode from terminal, do you have this printed ?
> 
> ```
> ERROR: _display_error_with_code: SceneShaderGLES3: Vertex Program Compilation Failed:
> ERROR: 0:470: Too many arguments to constructor of 'vec3'
> ERROR: 0:470: Too many arguments to constructor of 'vec3'
> ERROR: 0:470: Too many arguments to constructor of 'vec3'
> ```
@piiertho I have very similar error messages:
```
Godot-JVM: Godot-JVM: Editor mode, loading jvm from JAVA_HOME
Godot-JVM: Starting JVM ...
Godot-JVM: Loading bootstrap jar: /home/sipaha/Programs/godot/godot-bootstrap.jar
WARNING: JNI local refs: 33, exceeds capacity: 32
Godot-JVM: Starting GC thread
Godot-JVM: WARNING: No main.jar detected. No classes will be loaded. Build the gradle project to load classes
______SHADER_OUTPUT_____ 
ERROR: _display_error_with_code: SceneShaderGLES3: Vertex Program Compilation Failed:
0(470) : error C1068: too much data in type constructor
0(470) : error C1068: too much data in type constructor
0(470) : error C1068: too much data in type constructor
```
[editor-floats-error-log.txt](https://github.com/utopia-rise/godot-kotlin-jvm/files/6362006/editor-floats-error-log.txt)

**Comment by Sipaha** [comment]
I found that after JVM initialization std::to_string outputs comma instead of dot for float numbers:
![image](https://user-images.githubusercontent.com/3995047/115811840-a805f600-a41a-11eb-899e-e557c574ab1f.png)
Output:
```
Godot-JVM: 1.100000
Godot-JVM: 1,100000
```
Seems that is a problem with locale, but I don't know how to change it. This code:
```
const char* locale = "C";
std::locale::global(std::locale(locale));
```
Can't be compiled:
![image](https://user-images.githubusercontent.com/3995047/115812108-08953300-a41b-11eb-826f-84a6473537f9.png)

**Comment by Sipaha** [comment]
I found a workaround for Ubuntu:

Settings -> Region & Language -> Formats -> United States

![image](https://user-images.githubusercontent.com/3995047/115814072-96bee880-a41e-11eb-8600-bb87c9fd0de8.png)

Previously is was Russian Federation:

![image](https://user-images.githubusercontent.com/3995047/115814164-b8b86b00-a41e-11eb-89b2-5472ca9de059.png)

After this change everything works as expected with your build from release page.

**Comment by chippmann** [comment]
Yes i can confirm this. Once i set the locale of the VM i set up for this issue to russian, i get all of the mentioned issues in the editor.
Nice catch @Sipaha!
