### ISSUE TITLE
no nodes are created in the running instance

### ISSUE THREAD

**Issue by Frontrider** [utopia-rise/godot-kotlin-jvm#170]
When I try to run a test scene, I see that it's running, but nothing is instantiated in the game. The godot logo pops up for a second, then becomes hidden.
Manjaro, java 11.

![image](https://user-images.githubusercontent.com/6755034/115723242-0f229c80-a380-11eb-932b-259652ba40e0.png)
![image](https://user-images.githubusercontent.com/6755034/115723908-bdc6dd00-a380-11eb-9293-94b293e40666.png)

**Comment by chippmann** [comment]
Probably related to https://github.com/utopia-rise/godot-kotlin-jvm/issues/166

**Comment by chippmann** [comment]
@piiertho is this also resolved with #173 ?

**Comment by piiertho** [comment]
I confirme #173 resolves this.
