### ISSUE TITLE
Incorrect package name when creating a script using "Attach Script" dialog inside godot editor 

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#177]
```kotlin
package fixme // this should be a package name

import godot.Spatial
import godot.annotation.RegisterClass
import godot.annotation.RegisterFunction

@RegisterClass
class RootScene : Spatial() {

	// Declare member variables here. Examples:
	// val a = 2;
	// val b = "text";

	// Called when the node enters the scene tree for the first time.
	@RegisterFunction
	override fun _ready() {
		
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	@RegisterFunction
	override fun _process(delta: Double) {
		
	}
}
```

**Comment by CedNaru** [comment]
Yeah, we know for this one but I don't think it's possible to fix it.
When a script is created, Godot calls this function:
https://github.com/utopia-rise/godot-kotlin-jvm/blob/b14284fad29a7b216f2dd160132010f0d9487fbf/src/kotlin_language.cpp#L148.

This doesn't provide any information about where the file has to be created so we can't replace the "fixme" with the right package.

**Comment by Humberd** [comment]
Oh, that's a shame :/ I think it would be good to put it inside a documentation

**Comment by CedNaru** [comment]
ho wait, there may be a possibility.

Later godot set the path of the script created.
set_path is a virtual method of Resource:
https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/core/io/resource.h#L103

So I guess we can implement a way to replace the text here:
https://github.com/utopia-rise/godot-kotlin-jvm/blob/b14284fad29a7b216f2dd160132010f0d9487fbf/src/kotlin_script.cpp#L165
