### ISSUE TITLE
Kotlin debugger

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#178]
Is there a possibility to attach a debugger?

**Comment by CedNaru** [comment]
There is a way to do yes.
I guess we should add it to do it in the documentation.
Maybe @chippmann  can also find a way to make it easier with the IDEA plugin as well.

**Comment by piiertho** [comment]
Hello ! Here is documentation about command lines: https://godot-kotl.in/en/latest/advanced/commandline-args/

**Comment by chippmann** [comment]
An example command would be: `../../../../bin/godot.x11.tools.64 -v --jvm-debug-port=5005 test/tests.tscn`
Then you just need to attach a remote debugger

**Comment by chippmann** [comment]
Closing in favor of #184
