### ISSUE TITLE
[IDEA] Generating a project as a submodule results in putting all files in a root project directory instead of inside the submodule

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#179]
**Steps:**
```
GIVEN I have a random project opened in IDEA, for example "D:\Repositories\random_project"
AND I click right click on a root project directory name
THEN I click New -> Module
AND I select "Godot Kotlin JVM"
AND I click "Next" on a dialog creation window
AND I make sure that the "Content root" and "Module file location" are a nested directories inside current project, for example: "D:\Repositories\random_project\client-jvm"
THEN I click "Finish"
```

**Expected result:**
All the files created inside "D:\Repositories\random_project\client-jvm"

**Actual result:**
All the project files are not inside "D:\Repositories\random_project\client-jvm", but rather "D:\Repositories\random_project"

**Comment by CedNaru** [comment]
Nice catch. 
We also have another similar issue, the current Kotlin project setup for Godot Kotlin doesn't allow it to be put as a gradle subproject.

**Comment by chippmann** [comment]
To be honest I didn't even realize that the ModuleBuilder I implemented does not just function as a ProjectWizard, but also as a model creation wizard (now also the name makes sense to me ^^).
So yeah the case was never checked. Nice catch indeed.

**Comment by Humberd** [comment]
@CedNaru Just a moment ago I've managed to make it running as a gradle subproject while using a sibling library.

**Comment by chippmann** [comment]
> @CedNaru Just a moment ago I've managed to make it running as a gradle subproject while using a sibling library.

Yeah for that case we have a documentation page but just the project/module wizard does not accommodate this case.

https://godot-kotl.in/en/latest/advanced/custom_gradle_wrapper_path/

Just the gradle wrapper path setting is not yet in a release. Corresponding PR: #159
