### ISSUE TITLE
No "Export" annotation

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#180]
It looks like there is no "Export" annotation

![image](https://user-images.githubusercontent.com/10242142/115956512-829de880-a4fd-11eb-8fd4-0ceaf94d8c60.png)

![image](https://user-images.githubusercontent.com/10242142/115956524-8e89aa80-a4fd-11eb-81cc-14745b9dc88b.png)

**Comment by Humberd** [comment]
It might be connected with the fact that my IDE cannot find extension functions

![image](https://user-images.githubusercontent.com/10242142/115956751-e674e100-a4fe-11eb-9d6a-1a49df533334.png)

![image](https://user-images.githubusercontent.com/10242142/115956765-f8568400-a4fe-11eb-8607-d9ae97a68502.png)

**Comment by CedNaru** [comment]
The export annotation is not there yet. It's going to be in the next release.
For now you have to build the master to have it.

**Comment by CedNaru** [comment]
Also you can't use `<Any>` as the generic type for getNode. Because it as to be as least a `<Node?>`

**Comment by Humberd** [comment]
Doesn't really matter which type I put there, since the IDE doesn't even see the method with a generic type

**Comment by CedNaru** [comment]
After checking this works:
![image](https://user-images.githubusercontent.com/31470327/115957820-ea0b6680-a504-11eb-8188-5915ed169fa2.png)

But it's true that the IDE doesn't suggest the import. I had to manually add the right import.

**Comment by chippmann** [comment]
Closing in favor of #183 and #182 .
Feel free to reopen if you don't agree. If you find related issues, please make new ones.

Also to help with the export:
In the current stable release the `Export` annotation is not yet needed. Registered properties are automatically exposed to the editor.

**Comment by Humberd** [comment]
Well, if it should export the property automatically, then it doesn't work :/

```kotlin
@RegisterClass
class RootScene : Spatial() {
    @RegisterProperty
    lateinit var myScene: PackedScene

    @RegisterProperty
    var foo = 1f
}
```

![image](https://user-images.githubusercontent.com/10242142/115964275-f7841900-a523-11eb-8cdd-7a97872b05f9.png)

And yes, I've built it and run it.

**Comment by chippmann** [comment]
Did you reopen the editor?
On the current release, reloading is still broken. #161 fixed this and it will be in the next release. Until then new exported variables are only visible after reopening the editor.
