### ISSUE TITLE
Connecting signals doesn't work

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#181]
Given I have a signal on a button connected with a script in the parent node

```
[connection signal="pressed" from="VBoxContainer/Player1" to="." method="_on_Player1_pressed"]
```

And I have a function registered like this:

```kotlin
@RegisterClass
class LoginScene : PanelContainer() {
    @RegisterFunction
    fun _on_Player1_pressed() {
        println("clicked player1")
    }
}
```

Then I get this error:
```
ERROR: Object::emit_signal: Error calling method from signal 'pressed': 'PanelContainer(LoginScene.kt)::_on_Player1_pressed': Method not found..
   At: core\object.cpp:1260
```

**Comment by Humberd** [comment]
Funny thing is that if the registered method is `player` instead of `_on_Player1_pressed`, such that

```
[connection signal="pressed" from="VBoxContainer/Player1" to="." method="player1"]
```

Then everything works fine.

```kotlin
@RegisterClass
class LoginScene : PanelContainer() {
    @RegisterFunction
    fun player1() {
        println("clicked player1")
    }
}
```

**Comment by piiertho** [comment]
Hey ! You should not apply snake case in Kotlin. Respect Camel case, method will be auto converted to snake case for calling from engine. See https://godot-kotl.in/en/latest/user-guide/functions/

**Comment by Humberd** [comment]
I have some inconsistency:

## Case 1

Godot method name: `player_pressed`

Kotlin registered method name: `playerPressed`
![image](https://user-images.githubusercontent.com/10242142/115959331-078ffe80-a50c-11eb-806f-775ee026ee31.png)

Result: OK (there is also an icon next to a method)

## Case 2

Godot method name: `_player_pressed` (notice the underscore as a first char)

Kotlin registered method name: `PlayerPressed`
![image](https://user-images.githubusercontent.com/10242142/115959382-4920a980-a50c-11eb-9470-f9af0f852e4b.png)

Result: DOESN'T WORK (there is also an icon next to a method, why?)
```
ERROR: Object::emit_signal: Error calling method from signal 'pressed': 'PanelContainer(LoginScene.kt)::_player_pressed': Method not found..
   At: core\object.cpp:1260
```

**Comment by chippmann** [comment]
Again camel case. We don't support PascalCase which is your second example.
Only cameCase is supported for now.

**Comment by chippmann** [comment]
I guess i should add some IDE checks to mark inproper casing as error for exported functions and properties.

**Comment by chippmann** [comment]
We might also should improve the regex for function and property name conversion.

**Comment by TheElan** [comment]
It would be nice to have some hint (similar to how type hints are displaying) of how registered function will be named in godot after conversion. What do you think?

**Comment by chippmann** [comment]
Not sure if i can follow what hint you mean. Where do we display what with typehints? Can you make an example?
But i agree, displaying it would be nice. I have just not a good idea atm where and how it should be displayed

**Comment by TheElan** [comment]
I've never written an IDE plugin, so I am not sure if IDE would have an easy way to do this. I was thinking about something similar to type hint on a variable or function or function parameter at call, when you didn't provide it explicitly. 

For example, type hint displayed to the right off `contactDemand` val:
![image](https://user-images.githubusercontent.com/13066272/115973017-aa6f6980-a55a-11eb-8df4-04d5e7bfa909.png)

**Comment by chippmann** [comment]
Aah now i get what you mean. Yeah i see what i can do. Maybe something similar to what rider does with reference usage but I'm unsure if IDEA does support that. I'll try though.
![IMG_20210424_231820.jpg](https://user-images.githubusercontent.com/22662033/115973179-65940480-a553-11eb-9b84-7a2b11e64ab8.jpg)

**Comment by Humberd** [comment]
What about when we hover that icon on the left. Can we control it? I believe this info is rather for debugging purposes

**Comment by chippmann** [comment]
Sure that icon is from me. But I'd rather add a new gutter icon (that's the name of the icons on, well, the gutter) as you probably want that info not only for signals connected through the editor. I'll take this as a "last reort" if the rider like hint does not work

**Comment by TheElan** [comment]
If I am not mistaken you can connect to signals using strings in godot, it might not be the best idea to do this, but somebody might want to not only for debugging.

**Comment by chippmann** [comment]
Closing in favor of #194 and #195
