### ISSUE TITLE
Plugin in submodule creates godot.runtime.Entry in the root folder

### ISSUE THREAD

**Issue by sirnuke** [utopia-rise/godot-kotlin-jvm#190]
In a multiple module Gradle build, instantiating the Godot plugin in a submodule triggers the creation of `<root>/src/main/resources/META-INF/services/godot.runtime.Entry` rather than  `<root>/<module>/src/main/resources/META-INF/services/godot.runtime.Entry`.

It's not clear to me from a cursory glance at the codebase where the bug is, but presumably a SERVICE_FILE_DIR_PATH (or similar) is being set to the root of the Gradle project rather than the module where the plugin is being used.

**Comment by chippmann** [comment]
Nice catch.
Does also one gets generated for the module? So one in root and one in the module (they would look the same)?
Or just in the root?

**Comment by chippmann** [comment]
Related to #179

**Comment by sirnuke** [comment]
Looks like it does not.  I've created a wrapper in the submodule to get around #148 but it appears the services files is created in the root src directory regardless if I run gradle from the root or the submodule.

**Comment by chippmann** [comment]
Interesting. And can you run the project?
If not you could just copy the service file to the module dir and at it should work as a workaround.

**Comment by chippmann** [comment]
Line responsible for the issue: https://github.com/utopia-rise/godot-kotlin-jvm/blob/4e2b81e43015ba043d97e098df3a7a6cfe8225b7/kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotPlugin.kt#L58

**Comment by sirnuke** [comment]
Yes, with the service file in the correct module directory everything works fine.  It's just annoying that the file keeps getting recreated in the root directory every time I build.

The project in question is https://github.com/sirnuke/godot-kotlin-jvm-slf4j if you are interested.  The Godot project is in example/, with SLF4J bindings in lib/.

**Comment by chippmann** [comment]
Yeah that's annoying. As its a small change, It'll be in the next release for sure.

Nice thx. If you are on discord, consider sharing it there if you want others who might be interested to see it. If not I could do it for you if you want.

**Comment by sirnuke** [comment]
Yeah, I'll post it there once the project has fully sync'd to Maven Central.  Which will be any day now.... any day now....
