### ISSUE TITLE
Improve function/property name conversion regex

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#194]
Follow up to #181 
Make the signal conversion regex more permissive by allowing PascalCase and snake_case functions. Also functions with preceding `_` should be allowed.
Either this or completely disallow registering functions/properties which are not camelCase. The current way leads to too much error potential by not explicitly restricting or allowing it.

**Comment by CedNaru** [comment]
Is that really necessary to do it in Kotlin?
Godot C++ already has functions ready to do such a conversion.

**Comment by chippmann** [comment]
To convert cases?
Why didn't we use those for the registration then?
Can you link then?
But in any case if we use them it will be harder to supply IDE type hints requested in #195

**Comment by CedNaru** [comment]
https://github.com/godotengine/godot/blob/dc98144b99f35cc6446e297e2c6082d8c441d540/core/ustring.h#L259

**Comment by raniejade** [comment]
I prefer restricting it, users should follow kotlin's style.

**Comment by piiertho** [comment]
@CedNaru why would we use an engine while generating entry ? Or I did not understood the issue and this is not about entry ?

**Comment by CedNaru** [comment]
Closing this issues as signals are named like any other properties since Godot 4. The conversion of signal name has been removed.
