### ISSUE TITLE
Add debug hint for name conversion

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#195]
Follow up to #181 
Add name conversion hint to functions/properties/signals to indicate what the converted name is in godot.
Best case would be something similar to what rider is doing with function usages:
![115973179-65940480-a553-11eb-9b84-7a2b11e64ab8](https://user-images.githubusercontent.com/22662033/115987533-b8060d00-a5b5-11eb-82f6-8e4540d209a0.jpg)
Otherwise a new gutter icon should do the trick.

**Comment by TheElan** [comment]
Copy name on click would be nice, if possible.

**Comment by chippmann** [comment]
@TheElan Implemented with #248 including your request to copy the registered name on click.
