### ISSUE TITLE
Changing inheriting Class from api does not change existing scene files

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#198]
Here is how to reproduce the issue:
1- Create a class inheriting `Node`
2- Use this class to create a scene and save the scene
3- Change inheriting scene to Node2D (for example)
4- Try to call a method which is not present, `CanvasItem::getGlobalMousePosition` for example
5- Run scene. This should corrupt buffer because tscn will still have `Node` registered in it. `MethodBind::call` will fail in `TransferContext::call` because godot will have it as a `Node` and we'll try to use one of `MethodBind` template implem using `Node2D` as template arg. This will make cast fail and so instance will not be valid.
```
[node name="BattleWorld" type="Node"] //Here this does not change
script = ExtResource( 2 )
battle_map_scene = ExtResource( 1 )
debug_battle_party = ExtResource( 7 )
```

I don't know if that can be handled by IDE plugin ? @chippmann

**Comment by chippmann** [comment]
It is possible but i don't think that godot will pick up the file change and once you save the scene in the editor again it get's overwritten.
Godot is notoriously "bad" at picking up external file changes.
But we can try of course.
On that note: does this even work for gdscript if you just change the node type in the gdscript? I don't think so but i don't know for sure.

**Comment by chippmann** [comment]
Both cases (external change and only change extended type in gdscript) should be easy testable

**Comment by chippmann** [comment]
As discussed on discord: I don't think we should implement this. GDScript doesn't have this feature either nor does the editor pickup external file changes well enough. On top of that, such a feature could introduce some unwanted sideffects.
@piiertho can this be closed then?
