### ISSUE TITLE
Annotations naming

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#211]
Currently we are required to use annotations with a prefix `Register`, for example `@RegisterClass`, `@RegisterFunction`, etc. It looks like naming it with a prefix `Godot`, for example `@GodotClass`, `@GodotFunction` would be more clear and indicative that those symbols Godot is aware of. What do you think?

edit
Another argument for is that annotations are often nouns, not verbs, since they don't do anything by themselves.

**Comment by chippmann** [comment]
Hmm not sure about the `Godot` prefix though. This sounds more like this was a class or function from godot. Or is "owned" by godot.
If we would rename it i'd suggest `Registered` prefix. As it indicates that the class or member is registered in godot and not owned by it.

**Comment by CedNaru** [comment]
Closing this because replaced by #606
