### ISSUE TITLE
Strings from godot in kotlin ends with zero char

### ISSUE THREAD

**Issue by PavelSimonovCiteck** [utopia-rise/godot-kotlin-jvm#212]
Hello, 

I found a bug with strings which we receive from Godot side:

![image](https://user-images.githubusercontent.com/75359207/116643414-38a08100-a99b-11eb-9d02-04ce683eb996.png)

![image](https://user-images.githubusercontent.com/75359207/116643423-3d653500-a99b-11eb-9579-52b3443394af.png)

This is not specific for Dictionary. I found the same problem with file names while iterating by files in directory:

```
val dir = Directory()
dir.open("res://some_dir")
dir.listDirBegin(skipNavigational = true, skipHidden = true)
var file = dir.getNext() // file name also has zero at the end
while (file != "") {
   ...
   file = dir.getNext()
}
```

**Comment by CedNaru** [comment]
Maybe I did too much C++ recently but isn't it normal?
Strings always end with a 0 character so we can know when to stop reading the arr[]. This makes all Strings one character longer than the "useful" part.

**Comment by chippmann** [comment]
In cpp yes but not in kotlin IIRC:
![1](https://user-images.githubusercontent.com/22662033/116657987-97f89400-a98f-11eb-827c-970d2ce8212e.png)

**Comment by Sipaha** [comment]
@CedNaru it can be normal when methods working with strings know about it. If we use length() method or concatenate two strings zero char is ignored in gdscript and c++, isn't it?
