### ISSUE TITLE
Enums missing

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#215]
It looks like there is no enum such as `ButtonList`.

![image](https://user-images.githubusercontent.com/10242142/116733691-b0e36280-a9ec-11eb-80a6-291c64c5144a.png)

**Comment by piiertho** [comment]
Hi !
Those are in GlobalConstants as const.

**Comment by Humberd** [comment]
Yea, I found them. However, there are some discrepancies. For example there is an enum `Mesh.PrimitiveType.PRIMITIVE_LINE_STRIP` along with const properties in `Mesh.PRIMITIVE_LINE_STRIP` companion object. What is the reason to have an enum in one case and not in another?

**Comment by CedNaru** [comment]
It's not really up to us. We only follow what is written in the api.json in your last example we have both:

![image](https://user-images.githubusercontent.com/31470327/116800786-75d45280-ab04-11eb-8ce4-e47d07d5d7c3.png)
![image](https://user-images.githubusercontent.com/31470327/116800811-aae0a500-ab04-11eb-92a2-42e5dd625a6a.png)

**Comment by CedNaru** [comment]
We know that the way the api.json is generated for now (by Godot, it's not up to us again) is flawed.
C# bypassed by not using the api.json but directly querying the classDB inside Godot to fix those errors. We didn't do such thing for now.

**Comment by Humberd** [comment]
Ok, thanks for the effort.

**Comment by chippmann** [comment]
So can this be closed for now?
