### ISSUE TITLE
`InputEventMouseButton` has no `pressed` property getter

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#216]
Well, it has, but it looks like this:

```kotlin
open var pressed: Boolean
	  get() {
	    throw UninitializedPropertyAccessException("Cannot access property pressed: has no getter")
	  }
```

**Comment by piiertho** [comment]
This maybe is an api generation problem. Will look at it.

**Comment by piiertho** [comment]
I think we have a logic problem when generating api.
We generate api only if we have methods corresponding to property. (I don't remember why we did this)
Here, method has been commented: https://github.com/godotengine/godot/blob/8e68f2e5f48c66bfa80b9bb7746a488afb70086d/core/os/input_event.cpp#L530
So we have only setter, and property.
As there is no getter method (not property) in api json, the property is considered as not having a valid getter.
This [line](https://github.com/utopia-rise/godot-kotlin-api-generator/blob/df3f30233a04bc43324125f69194aab797dda833/src/main/kotlin/godot/codegen/Property.kt#L200) is never called in the case of `pressed` property of `InputEventMouseButton `

**Comment by Humberd** [comment]
Then how can I check if I have pressed the button? C# has this exact property.

**Comment by CedNaru** [comment]
I don't know what commit it was in the Godot but if I take the 3.2 or 3.3 stable commits, that getter is not commented.

**Comment by CedNaru** [comment]
That's something we have to fix in the api gen, you can't check that for now.

**Comment by Humberd** [comment]
I've found a workaround. Previously my script set up a flag when the right mouse button was being pressed:

```kotlin
@RegisterFunction
override fun _input(event: InputEvent) {
    if (event is InputEventMouseButton) {
        if (event.buttonIndex == GlobalConstants.BUTTON_RIGHT) {
            // fixme: should be event.pressed
            mousePressed = event.doubleclick
        }
    }
}
```

Now I defined an action in `Project -> Project Settings -> Input Map`
![image](https://user-images.githubusercontent.com/10242142/116807685-c663a400-ab34-11eb-9c86-8cf0dcfe44bd.png)

Then used it like this:

```kotlin
@RegisterFunction
override fun _input(event: InputEvent) {
    if (mousePressed && event.isActionReleased("move")) {
        mousePressed = false
    }

    if (!mousePressed && event.isActionPressed("move")) {
        mousePressed = true
    }
}
```
