### ISSUE TITLE
Godot editor filesystem search shows generated Kotlin classes

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#220]
Is there a way to filter them out?

![image](https://user-images.githubusercontent.com/10242142/116816438-32a8cc80-ab62-11eb-8b8b-8559fd1711f1.png)

**Comment by CedNaru** [comment]
Not sure how to prevent this one.  I have to test if a .gdignore would work but I doubt it.
This can be a source of errors as well because technically nothing prevents someone to attach an entry file to a node.

**Comment by Frontrider** [comment]
Adding this to the build file/plugin is a permanent fix:
```
//setup gdignores
fun setupGdIgnore(){
    buildDir.mkdirs()
    if(buildDir.exists()) {
        File(buildDir,".gdignore").writeText("")
    }
    File(project.rootDir,"gradle/.gdignore").writeText("")
}
//run setup, so building it once/importing into intellij does the work
setupGdIgnore()

//make clean run the function as well, so the build folder can be ignored again.
tasks.named("clean"){
    doLast {
        setupGdIgnore()
    }
}
```

You will always have a gdignore in the build folder, and in the gradle folder (where the wrapper is).
