### ISSUE TITLE
Can't run Linux build

### ISSUE THREAD

**Issue by dector** [utopia-rise/godot-kotlin-jvm#224]
With the 3.2 build I have error when trying to run editor:

```
./godot.x11.opt.tools.64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./godot.x11.opt.tools.64)
```

Indeed,
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25| grep GLIBCXX 
```

shows that `3.4.25` is the latest version in `libstdc++6 8.3.0-6`.

I have `Debian Buster` and it's the newest package in it. There is version 10+ in Sid but it's not compatible.

Original Godot 3.2 and 3.3 builds works without this issue. Is it possible to bundle required library? Thanks.

**Comment by piiertho** [comment]
I think we should better try to build without std library. Godot have std and non std builds.
Anyway I don't think we should bundle this library. This would mean embedding CRT for Windows

**Comment by chippmann** [comment]
I think the main problem is that we use `ubuntu-latest` to build the binaries. But to build portable binaries on linux, one should use the oldest OS one still wants to support, to build the binary. In our case, this would be `ubuntu-18.04` which is the oldest LTS version of ubuntu still supported by github actions.
Just changing the runner to use `ubuntu-18.04` should be enough to fix this particular issue.
