### ISSUE TITLE
Maybe override the override operator or add and extends operator

### ISSUE THREAD

**Issue by WilliamBehrens** [utopia-rise/godot-kotlin-jvm#238]
I'm not too familer with operator overloading in kotlin(if it even exist) but I have noticed that if I want to extend a function from a parent class rather then override it completely I have to call super.functionName() at the beginning which is really annoying. I may be the only one who thinks this is an issue but I'm open to hearing solutions to it(overriding override, adding an extends keyword, or have registered functions call the parent function automatically if that's possible).

**Comment by TheElan** [comment]
I believe keyword/annotation won't help to achieve much "improvement", as it will basically replace one explicit declaration of calling super with another (albeit shorter).

It is a part of language design, so we can see when you want to get super's functionality.  If you change this,  it can be very confusing for people used to kotlin. If I understand correctly one of the goals of this project is to bring as much of kotlin-like as possible, so you don't need to learn too much new things (besides kotlin and godot) to start working on a game.

Inheritance is also often overused and may be not the best solution for the problem. There this notion of "delegation over inheritance" which is quite helpful when you want have clear picture of what is going on and have less coupling, as hierarchies can get out of control.

**Comment by CedNaru** [comment]
Yeah, what you are asking is impossible to do, override is not a keyword you can overload in the first place.
It has nothing to do with our module in the first place, it's just how the language is in the first place.
And if super was called by default, it would lead to a lot of confusion in the first place. Sometimes you just want to completely change the behavior of a method, not extend it. There is also the matter of where you want to call super: Before everything? After everything? In the middle?
