### ISSUE TITLE
`JVM_` prefixed `VariantType` types not visible in inspector.

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#243]
Types like `Int` are not visible in inspector because godot doesn't know the ordinal of `JVM_INT`.
Long on the other hand works as the ordinal of `VariantType.LONG` is correct.

**Comment by CedNaru** [comment]
Most likely an error when we copy the ordinal in the buffer. The JVM_ types are not supposed to put their own ordinal in it but the one of the enum they "wrap".
