### ISSUE TITLE
Signals that aren't registered with `@RegisterSignal` still work in the editor

### ISSUE THREAD

**Issue by alicerunsonfedora** [utopia-rise/godot-kotlin-jvm#265]
I've noticed that if one forgets to decorate their signal in a class with `@RegisterSignal`, the signal will still work in the editor, but not in an exported build. After some discussion, it might be there's a Kotlin-specific scoping thing that allows it work in Kotlin, but not in Godot.

**Version:** 0.2.0-3.3.2
**Platform:** macOS

**Steps to reproduce**:  
1. Download https://github.com/alicerunsonfedora/planting-uneasy-feelings/tree/1.0.0-SNAPSHOT.
2. Follow build instructions to build the project.
3. Notice that it works in the editor.
4. Export to any platform.
5. Notice that it doesn't work in the export.

**Expected behavior**  
The editor causes a build error, or the signal doesn't work when debugging in the editor (i.e., it shows the same error from the exported builds)

This is the error that should pop up in the editor, which should prevent the player from advancing to the rest of the game:

```
ERROR: connect: In Object of type 'PopupDialog': Attempt to connect nonexistent signal 'dialogue_finished' to method 'Node2D.on_dialogue_finish'.
   At: core/object.cpp:1500.
ERROR: emit_signal: Can't emit non-existing signal "dialogue_finished".
   At: core/object.cpp:1192.
```

**Actual behavior**  
The editor still accepts it just fine.

**Comment by piiertho** [comment]
Hello !
So if I understand correctly, you don't have :
```
ERROR: connect: In Object of type 'PopupDialog': Attempt to connect nonexistent signal 'dialogue_finished' to method 'Node2D.on_dialogue_finish'.
   At: core/object.cpp:1500.
   ``` 
when calling connect with editor version ?

If that's it, when reading code I see few lines on godot code that differs in editor mode:
https://github.com/godotengine/godot/blob/b973f997ff56bd9ad4c0a521e123cc4aee13135d/core/object.cpp#L1494
 
 But as far as I understand your script was valid :/

**Comment by alicerunsonfedora** [comment]
This was with editor version 0.2.0-3.3.2.

**Comment by CedNaru** [comment]
Closing because dead issue for more than 2 years and signal got entirely reworked with Godot 4.
