### ISSUE TITLE
IDEA plugin only supports 2021.1.x

### ISSUE THREAD

**Issue by alicerunsonfedora** [utopia-rise/godot-kotlin-jvm#267]
It appears that the latest stable version of the IDEA plugin only supports IntelliJ 2021.1.x:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/13445064/131425341-2bde32a0-dfde-40c8-9ba3-5498fa9b23ad.png">

From the discussion in the Discord, it seems that this isn't supposed to be the case and that it should support multiple versions.

**Comment by chippmann** [comment]
This is to be expected.
We cannot build plugin version in advance. At the time of the last release, IDEA 2021.1.3 was the latest one. With the next release we can update the plugin.
If you need a new version now, you need to build it yourself with the necessary changes done in https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/plugins/godot-intellij-plugin/build.gradle.kts
