### ISSUE TITLE
Missing extensions for disconnect() and isConnected() methods

### ISSUE THREAD

**Issue by CedNaru** [utopia-rise/godot-kotlin-jvm#272]
Currently, we provide a lot of extensions so users can connect to signal in a more Kotlin way using function references instead of unsafe strings.

But we never provided the sibling functions of those: disconnect and isConnected.
It means if someone wants to disconnect a signal ( and check if it's already connected before), one has to use the original functions that use a string.

**Comment by chippmann** [comment]
@CedNaru Why did you close this?
