### ISSUE TITLE
Unable to change minSdkVersion of the app

### ISSUE THREAD

**Issue by moraguma** [utopia-rise/godot-kotlin-jvm#281]
**Platform:** Windows
**Version:** 0.2.0 - 3.3.2

When isAndroidExportEnabled is set to true and the project has a dependency on a library that requires minSdkVersion 26, I get the following error:

```
Uncaught translation error: com.android.dx.cf.code.SimException: ERROR in br.unicamp.cst.util.CodeBuilder.executeMethod:(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
```

I'm used to being able to change the minSdkVersion of the project on the build.gradle file, but the project doesn't seem to define the minSdkVersion anywhere. Also, by default, [Godot has its minSdkVersion as 18](https://github.com/godotengine/godot/blob/25b98e4842b910c07cfa95a797ac9bf43e7bfd94/platform/android/SCsub#L101) but, according to the error message, the minSdkVersion being used is 13, so I don't know where that's coming from.

The project builds and runs as expected on Windows as long as isAndroidExportEnabled is set to false, and Android builds were also working fine before adding my library. The Android SDK version I have installed is 30, and the ANDROID_SDK_ROOT environment variable is set to its folder. I had also tried to setup an [Android Custom Build](https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html), but changing the minSdkVersion on its build.gradle didn't seem to have any effect.

Here's what build.gradle.kts looks like

```
plugins {
    kotlin("jvm") version "1.4.32"
    id("com.utopia-rise.godot-kotlin-jvm") version "0.2.0-3.3.2"
}

// ...

godot {
    isAndroidExportEnabled.set(true)
    dxToolPath.set("${System.getenv("ANDROID_SDK_ROOT")}/build-tools/30.0.3/dx")
}
```

**Comment by chippmann** [comment]
To sum up some findings and discussions from discord:
In the current release we still use the old `dx` tool. The first question is whether this issue still exists on the current master version which uses the newer `d8` tool for creating the `dex` files.
Still we need to expose more of the configuration of the `d8` tool (commandline args. see: https://developer.android.com/studio/command-line/d8) in a typesafe way in our gradle dsl.

Hints to where to make the needed changes for that:
- Gradle Extension (the DSL configuration object): https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt
- Main Dex Jar Task: https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/createMainDexFileTask.kt
- Bootstrap Dex Jar Task: https://github.com/utopia-rise/godot-kotlin-jvm/blob/master/kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/tasks/android/packageBootstrapDexJarTask.kt

**Comment by piiertho** [comment]
Is this issue still here ? I think I fixed it with https://github.com/utopia-rise/godot-kotlin-jvm/pull/295

**Comment by chippmann** [comment]
I think it can be closed.
@moraguma feel free to reopen if you find any issues with it
