### ISSUE TITLE
Implement support/usage of `Gradle JVM Toolchain`

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#287]
See: https://blog.jetbrains.com/kotlin/2021/11/gradle-jvm-toolchain-support-in-the-kotlin-plugin/
This would greatly improve the user experience and would remove a common source of error.
It also would simplify the creation of a jlink gradle task for our gradle plugin

**Comment by CedNaru** [comment]
Closing as JVM Toolchain is now supported in the gradle plugin.
