### ISSUE TITLE
Implement Godot 4 changes on the JVM side

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#305]
@piiertho has already done most of the cpp changes to support Godot 4.
But many things on the JVM side still need to be changed.

Namely the shared buffer glue code, class renaming, and new method implementations on core types

Many areas which need changing are already marked with a todo: `//TODO/4.0`.

**Comment by piiertho** [comment]
We should keep in mind cop code still needs some adaptations, even in glue code

**Comment by Ayfri** [comment]
Any update ?
