### ISSUE TITLE
Improve handling of commandline args

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#31]
We now have quite a few command line arguments that one can supply to change how the jvm/cpp interaction works.
It would simplify things a lot if we had a table in the readme that lists all available arguments and their functionality.
If written well, this can be later copied one to one to the documentation.

**Comment by piiertho** [comment]
I would add the creation of a conf struct on cpp side, to enhance maintainability? 
For now cmd parsing is in init method of GDKotlin singleton, which is dirty.

**Comment by chippmann** [comment]
Changed title and thus subject of this issue as the actual documentation was already done with https://github.com/utopia-rise/godot-kotlin-jvm/pull/79
