### ISSUE TITLE
Document why this language binding is still a module and not a `GDExtension` in Godot 4

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#311]
For the time being we have the same problems and limitations as `C#` has regarding the new `GDExtension` system.
These namely are:
- lack of namespace support (not a big issue for us as we already handled that)
- lack of state keeping in the editor if classes are rebuilt while the editor is open (<- THE big issue)

These issues/limitations need to be documented in a more detailed way in our documentation at an easy to access location as the question why we are still a `module` while `GDExtension`'s are a thing will pop up frequently in to future.

**Comment by CedNaru** [comment]
Issue 2 years old, and we still haven't written anything about it. I think it's safe to close anyway as we decided to soon make this binding compatible with gdextension.
