### ISSUE TITLE
com.utopia-rise:godot-library:0.3.4-3.4.4 is not getting pulled correcly by maven / gradle

### ISSUE THREAD

**Issue by teichholz** [utopia-rise/godot-kotlin-jvm#325]
For some reason the godot-library does not get pulled correctly. Specifying the dependency manually does not help. Libraries under Project Structure in IntelliJ shows that no classes were installed but has an entry for godot-library. I tried to pull joda-time as a dependency, which worked just fine.

I'm on nixos which might cause weird behavior but this still seems weird to me.

Running ./gradlew build returns:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':packageBootstrapJar'.
> Could not resolve all dependencies for configuration ':bootstrap'.
   > Could not find com.utopia-rise:godot-library:0.3.4-3.4.4.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/utopia-rise/godot-library/0.3.4-3.4.4/godot-library-0.3.4-3.4.4.pom
       - https://repo.maven.apache.org/maven2/com/utopia-rise/godot-library/0.3.4-3.4.4/godot-library-0.3.4-3.4.4.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

My Java/Kotlin knowledge ends here, help is appreciated.

**Comment by piiertho** [comment]
Hello ! Don't have problem on my side to resolve and download our dependencies using the gradle plugin.  
Can you provide your gradle build script ?

**Comment by teichholz** [comment]
Hey,

my build.gradle.kt is

```
plugins {
    id("com.utopia-rise.godot-kotlin-jvm") version "0.3.4-3.4.4"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.utopia-rise:godot-library:0.3.4-3.4.4")
    implementation("joda-time:joda-time:2.10.6")
}

godot {
    isAndroidExportEnabled.set(false)
    d8ToolPath.set(File("${System.getenv("ANDROID_SDK_ROOT")}/build-tools/31.0.0/d8"))
    androidCompileSdkDir.set(File("${System.getenv("ANDROID_SDK_ROOT")}/platforms/android-30"))
}
```
I'm not behind any company proxy.

**Comment by piiertho** [comment]
Only thing you should need is
```kotlin
plugins {
    id("com.utopia-rise.godot-kotlin-jvm") version "0.3.4-3.4.4"
}

repositories {
    mavenCentral()
}
```

But the thing I don't understand is why you can't get https://repo.maven.apache.org/maven2/com/utopia-rise/godot-library/0.3.4-3.4.4/godot-library-0.3.4-3.4.4.pom
If you try to access it from a browser, does it display the pom ?

**Comment by teichholz** [comment]
I can't access the pom from chromium
