### ISSUE TITLE
[Idea Plugin] IDEA 2022.1 support?

### ISSUE THREAD

**Issue by 19lmyers** [utopia-rise/godot-kotlin-jvm#332]
I was looking to get started with this in a project of mine, but unfortunately the Idea plugin isn't compatible with IDEA 2022.1 right now.

**Comment by chippmann** [comment]
Yeah we discussed this in Discord. I'll provide an update which should be compatible with future IDE releases out of the box as soon as I've got some time for it. Probably by the start of next week.
Until then you either have to use an older IDE version (you can easily install multiple versions of the IDE through Jetbrain's [Toolbox App](https://www.jetbrains.com/toolbox-app/), or you ditch our plugin for now (it's not mandatory to use, just a helper) until we provide the update.

**Comment by chippmann** [comment]
[Notes from our discussion on Discord for Documentation purposes]:
The underlying issue we have currently is that we have to provide an IDE plugin update for each IDE version released by jetbrains as we define the compatibility version [here](https://github.com/utopia-rise/godot-kotlin-jvm/blob/cbdb5f27e835dc34b09fa1d70b0509561b013446/kt/plugins/godot-intellij-plugin/build.gradle.kts#L42) for example.
As we provide a pretty strict max version, our plugin is "incompatible" with anything newer.

As most of the time with IDE updates the only changes we need to make to our plugin is rising these version numbers and release again, we decided to define the max version in a non strict fashion like `999.*`. This would mark our plugin as compatible with (possibly) all future IDE updates and we only have to provide updates for IDE versions which introduce breaking changes for components our plugin interacts with.
As we currently have no automated tests which run periodically for new IDE versions and are capable of detecting if such a breaking change occurs, we will rely on manual testing and issues being created for such breaking changes by users of the plugin for now, until we find a suitable way of testing this. This seems like "the lesser evil" for now at least.
