### ISSUE TITLE
Add error dialog if export fails

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#354]
Currently if the export fails to add the jre or any of the jar file we create, we just print that to the log but the editor does not display any error.
Hence users who either run the editor without any console, or just don't pay attention, won't notice that the export failed.

What makes matters worse is that in some cases the resulting binary is even created, leading to the false conclusion the export was successful.

**Comment by CedNaru** [comment]
Done since #632
