### ISSUE TITLE
Editor crashes when opening a project if JAVA_HOME is not defined

### ISSUE THREAD

**Issue by mrParabol** [utopia-rise/godot-kotlin-jvm#361]
this issue has been reported before but the issue still persists.
debian linux- buster
java path : /home/deepin/.sdkman/candidates/java/current/bin/java
java version : openjdk 17.0.4.1
godot : 3.5.1- 0.5.0
godot-JVM intellijidea addons :0.5.0

I added it to bashrc like this:
export JAVA_HOME="/home/deepin/.sdkman/candidates/java/current/bin"

**Comment by mrParabol** [comment]
java yolunu bir üst dizini(java path : /home/deepin/.sdkman/candidates/java/current (one directory above the bin folder) ) belirttim ve projemin içerisinde jre-amd64 klasörü oluşturdum.daha sonra bu jre-amd64 klasörünün içerisine java'nın yüklü olduğu klasördeki lib klasörünü kopyaladım.and problem solved.

**Comment by Ultipuk** [comment]
```bash
# Find your java executable with this:
readlink -f $(which java)

# I'v got /usr/lib/jvm/java-26-openjdk/bin/java
# But to set JAVA_HOME we need jdk path, which is
# /usr/lib/jvm/java-26-openjdk for me.

# Set JAVA_HOME variable:
export JAVA_HOME=/usr/lib/jvm/java-26-openjdk

# You can make it available for all programs
# within this user session via systemd:
systemctl --user import-environment JAVA_HOME

# Now you don't need to run Godot from console.
```
