### ISSUE TITLE
Registering properties of custom interfaces breaks code generation

### ISSUE THREAD

**Issue by exigow** [utopia-rise/godot-kotlin-jvm#371]
Hi,

this combination produces invalid code:
1. class extending `Node`
2. such class implementing interface with `var` property
3. such property with `@Export` annotation

I think this scenario should be supported. You often want to create abstraction with common property across different implementations (for example, "game object" and "health" value). Changing this value in editor should be also available.

### Steps to reproduce

Version: `0.5.1-3.5.1`

```kotlin
interface TestInterface {
	var testProperty: String
}
```
```kotlin
@RegisterClass
class TestNode : Node(), TestInterface {
	@Export
	@RegisterProperty
	override var testProperty: String = ""
}
```
### Result

Compilation fails. Class in `build/generated/` contains redundant `override` keyword. Removing `override` manually seems to work but code is replaced on next `build` task.

```kotlin
public open class TestNodeRegistrar : ClassRegistrar {
	public open override val testPropertyDefaultValueProvider: () -> String = { """""" }
	public override fun register(registry: ClassRegistry): Unit {
		with(registry) {
			registerClass<TestNode>("res://src/main/kotlin/test/TestNode.kt", "godot.Node", TestNode::class, false, "Node", "test_TestNode") {
				constructor(KtConstructor0(::TestNode))
				function(TestNode::_ready, NIL, KtFunctionArgument(NIL, "kotlin.Unit"), DISABLED.id.toInt())
				property(TestNode::testProperty, STRING, STRING, "kotlin.String", NONE, "", testPropertyDefaultValueProvider, true, DISABLED.id.toInt())
			}
		}
	}
}
```

PS: Thanks for working on this binding. It makes me happy by allowing me to use Godot with Kotlin.

**Comment by chippmann** [comment]
Changed the title to the "real" problem.
Reason for the problem: I handle interfaces as abstract classes in the entry generation by mistake.
Will fix it asap.

**Comment by exigow** [comment]
Thanks, @chippmann.
