### ISSUE TITLE
No error when registering a generic class

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#372]
When we register a generic class we don't have any warning from intellij plugin.  
We see it does not work only when compiling, because Registrar does not compile (as it misses generic parameter)

Example to reproduce:
```kotlin
@RegisterClass
class Vertex<T> : Resource(), IVertex<IPositionFinder>
```

**Comment by chippmann** [comment]
Hmm do you have a bit more context?
Do you also want to register generic functions and properties? Or are no members with generic usages registered?

**Comment by piiertho** [comment]
This does not compile, and this is expected. But intellij plugin does not complain, I think it should.

**Comment by chippmann** [comment]
True we cannot register anything generic as we don't know the supported types.
Ok will add a corresponding error to the IDE plugin
