### ISSUE TITLE
Exported properties should be sorted by declaration order

### ISSUE THREAD

**Issue by exigow** [utopia-rise/godot-kotlin-jvm#384]
Version: `0.5.1-3.5.1`

Exported variables in Kotlin sometimes don't keep order like declared, especially if we use different types.

This non-deterministic behaviour is problematic because Godot Editor has issues with keeping old values in TSCN file when order has changed - values can be randomly nullified, even when class is written in GDScript. When "re-order" occurs, properties need to be manually assigned again in editor.

Code to reproduce:

```gdscript
extends Node

export var a: NodePath
export var b: Texture
export var c: Texture
```

```kotlin
@RegisterClass
class Test : Node() {

	@Export
	@RegisterProperty
	var a: NodePath? = null

	@Export
	@RegisterProperty
	var b: Texture? = null

	@Export
	@RegisterProperty
	var c: Texture? = null

}
```

Screenshot shows invalid order:

![export_order_issue](https://user-images.githubusercontent.com/5013708/202909498-8b897444-e378-44df-a154-1fb6cc472409.png)

Expected behaviour:

Kotlin properties order should be `A`, `B`, `C`.

**Comment by chippmann** [comment]
@CedNaru or @piiertho ; do you know if we can enforce the order during registration? I mean theoretically it should stay the same from the entrygen and the symbolprocessor but I'm unsure whether this is true or not. Also if not, this will be hard to do without ordering the members alphabetically
