### ISSUE TITLE
Android App won't install - Invalid Package

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [utopia-rise/godot-kotlin-jvm#397]
When attempting to install the Godot editor apk, I get the following message:
 ![App not installed as package appears to be invalid](https://user-images.githubusercontent.com/60950821/205445333-9b342d72-a9c6-4dfb-a22f-2a7c8384958a.jpg)

I'm using a Samsung Galaxy Note 20 Ultra with Android 13.

**Comment by piiertho** [comment]
Hello !
So if I understand correctly, you're trying to install your exported game on your device ?
Can you provide a small project to reproduce the error ?

**Comment by Stephen-Hamilton-C** [comment]
Not a game, the editor itself. When I try to install the editor apk from https://godotengine.org/download/android, I get the error

**Comment by chippmann** [comment]
We currently do not support the editor on android.
The apk files in the releases on our repo are only export templates for exporting your game to android.
For problems with the official android editor, you should open an issue on the official godot repo.

But this project does currently not support the editor on android.
