### ISSUE TITLE
Control `rect*` properties cannot be changed

### ISSUE THREAD

**Issue by exigow** [utopia-rise/godot-kotlin-jvm#417]
Example: 

```kotlin
@RegisterClass
class Test: Control() {

  @RegisterFunction
  override fun _process(delta: Double) {
    rectPosition.x = 1.0 // this won't work
    rectSize.x = 1.0 // same
    rectPosition = Vector2(1.0, 2.0) // this won't compile
  }

}

```

**Comment by piiertho** [comment]
`rectPosition = Vector2(1.0, 2.0)` does not work as `rectPosition` is a `val`.  
`rectPosition` and `rectSize` getters return copy of the actual value, so you're modifying a copy, hence why this does not work.  
In order to set the position, you should use `setPosition` method.

**Comment by exigow** [comment]
@piiertho, i thought it was a bug. Thanks for the explanation.
