### ISSUE TITLE
Generate `gdj` and `kt` files from within the godot editor

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#445]
With https://github.com/utopia-rise/godot-kotlin-jvm/pull/441 we introduced the concept of "registration files".

We now need a way to generate a `gdj` and a `kt` when the user creates a new script inside the editor.

One way could be with a custom resource saver where we not only save a `gdj` file, but also create a corresponding `kt` file in the root package.

**Comment by CedNaru** [comment]
I think this proposal has to be paired with #500. It would make the implementation much easier if the .gdj files could be freely placed inside the godot project. The .kt and .gdj would then both be created next to each other. No need for custom C++ logic to place them in the correct directory (directory only known by our gradle plugin by the way).

**Comment by CedNaru** [comment]
Forgot to close that issues. We create both scripts + Java in the editor now.
