### ISSUE TITLE
Update documentation for Godot 4

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#447]
There are quite a lot (and also significant) changes with Godot 4 for this binding.

The documentation should be updated to reflect these changes.

Together with this, we should probably also do https://github.com/utopia-rise/godot-kotlin-jvm/issues/283

**Comment by asm0dey** [comment]
I don't quite understand if the 4th version is supported. If so, I would expect at least to see a release in the "Releases" section. So I assume it's not ready yet. Am I right?
