### ISSUE TITLE
Confusing error when Android SDK is missing "platforms" folder

### ISSUE THREAD

**Issue by nicola-sorace** [utopia-rise/godot-kotlin-jvm#494]
Was getting this error when trying to compile a Godot-Kotlin project:
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/13591769/98f54782-3b6c-4bf0-8eca-2d6683bbceb1)

Eventually worked out that something was looking for `$ANDROID_SDK_ROOT/platforms`, which didn't exist on my system. The `ANROID_SDK_ROOT` environment variable was set, but the platforms folder was empty. I had to install the [android-platform](https://aur.archlinux.org/packages/android-platform) package for it to work. Alternatively, un-setting `ANDROID_SDK_ROOT` also seems to work since I'm not compiling for Android.

Error message could probably be made clearer. Took a lot of effort to track down what the error was.

**Comment by CedNaru** [comment]
Thanks for the issue.
It seems the issues comes from [here](https://github.com/utopia-rise/godot-kotlin-jvm/blob/638c3d4767f057389d736384c521105e6d2005a3/kt/plugins/godot-gradle-plugin/src/main/kotlin/godot/gradle/GodotExtension.kt#L172C13-L172C26).

We assume the platforms folder exists if we find the android sdk root. This assumption causes an error later in the code.
