### ISSUE TITLE
Embedd JRE in pkg and accessible through res://

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#50]
The JRE should be embedded inside the `pkg` file and from there be accessible through the `res://` path. This makes it so that shipping the JRE separate is obsolete.

**Comment by piiertho** [comment]
I'm not sure anymore about this one.
On iOS jvm would be embedded in exe and on desktop it makes sense to have it in a subfolder. On Android this is already here.
I think we should better copy jre folder in Export plugin we're making for embedded jar.
