### ISSUE TITLE
CI Deploy Libraries and Pre-Built engines

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#51]
Implement github actions to deploy:
- prebuilt engines on each release and for snapshots
- Libraries, annotation processor, etc. to bintray

**Comment by chippmann** [comment]
We cannot use bintray anymore as it get's sunsetted. We need to publish to mavenCentral now which also requires us to:
- sign our artifacts with a GPG key (we need to store them accessible to all maintainers)
- add sources (we would anyways)
- add docs (maybe using dokka?)

This also rises some questions about where to host the engine builds.
I suggest github with release artifacts

**Comment by abueide** [comment]
May I suggest using jitpack.io? Might be easier than setting up all the mavencentral stuff, and then we just need to create a tag and it will build the artifacts so we don't have to use a script + secrets to upload to mavencentral.

**Comment by chippmann** [comment]
> May I suggest using jitpack.io? Might be easier than setting up all the mavencentral stuff, and then we just need to create a tag and it will build the artifacts so we don't have to use a script + secrets to upload to mavencentral.

He nicely sums up why I'm against using jitpack: https://twitter.com/saketme/status/1357087957090467841?s=20

Especially point 3. The `godot-library` project takes a long time to build because of the huge amount of generated code. So the gradle task for the first user that tries to pull it will definitely timeout.
Furthermore, jitpack is not centralized.
Just because it's more convenient and easier for us, should not qualify to accept these (IMO) unnecessary downsides.
That said: we already did the annoying part of the mavenCental setup. The only thing left is to actually publish the artifacts once we think they are ready.
