### ISSUE TITLE
Editor plugin slows intellisense down

### ISSUE THREAD

**Issue by Frontrider** [utopia-rise/godot-kotlin-jvm#520]
Editor plugin seems to slow intellisense down, sometimes to the point where it can no longer provide assistance. I do not know exactly what is happening, only that disabling the plugin gets idea back into working order.

**Comment by CedNaru** [comment]
I experienced the same issue as well. 
The IDE is taking forever to parse the code when the plugin is running. It runs with a small project, but when opening something like our own repo, it's extremly slow. I could literally see the code parsing happening in real time, like one line of code getting "validated/colored" every 2 seconds.

**Comment by Frontrider** [comment]
I had it enabled on a large non-godot project and intellisense just died outright.
