### ISSUE TITLE
Attach node script getting invalid path and invalid extension.

### ISSUE THREAD

**Issue by subash1** [utopia-rise/godot-kotlin-jvm#525]
Hi Guys,

![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/6370601/34e62153-5e71-4381-a667-47b34e24a84d)

Seems attach script by default with *.kt file extension filter. If i choose kotlin file, it ends up with unable to open script error.

i am using the version 0.7.2-4.1.2

Thanks in advance

**Comment by CedNaru** [comment]
Our bad.
When we switched from using .kt to .gdj, we forgot to properly change this part of the editor, so it's still expecting a .kt.
For now, you can just drag and drop scripts from the filesystem to a node as an alternative.

**Comment by CedNaru** [comment]
After digging a bit about how this Godot UI works, here what I found.
The UI to create a script and/or attach it is the same. Behind the hood it's just using the implementations of ScriptLanguage registered to the engine to find the correct extension and templates. If you try to create an already existing script, it switch to "attach Node" mode.

Once you validate this window, there are 2 consequences:
- In the case of script creation, the script file is saved and Ref<Script> is created, then a signal script_created signal is emitted. [Creation code](https://github.com/godotengine/godot/blob/09946f79bd8215b2c6332de8821737580909a91c/editor/script_create_dialog.cpp#L357)
- In the case of script attachement, the provided script file is loaded, then a script_created signal is emitted.  [Attachment code](https://github.com/godotengine/godot/blob/09946f79bd8215b2c6332de8821737580909a91c/editor/script_create_dialog.cpp#L369)
- Another part of the godot editor receives the signal with the Ref<Script> in it and attach it to the Node.

We have very little control over the whole process. Our only leeway is our ScriptLanguage and ResourceSaver/Loader implementations.

On our side we want the following behavior :
- Creation of the .kt and .gdj file at the same time.
- Attachment of a .gdj

The proper "workflow" is to create a .kt and attach a .gdj. But this is tricky when we have to considerer that a ResourceLoader and Saver have to manipulate the 2 files at the same time. 
If done poorly, it could lead to getting duplicated .kt whenever someone select a .gdj, which would also make the editor "inspect" it and save it automatically. We need a way for a .gdj file to known from which .kt file it comes from to avoid this kind of mistake, the 2 files are not necessarily (in practice, almost never) at the same location. So I think the data has to be stored somewhere, directly inside the .gdj file or as part of the KtClass held by KotlinScript.
