### ISSUE TITLE
Examples to test setup & demonstrate specific features

### ISSUE THREAD

**Issue by travisfw** [utopia-rise/godot-kotlin-jvm#526]
I'm just looking for a working example I can use to ensure I can actually build and run a Godot-Kotlin app. Most game engines have at least a hello-world type project that shows a teapot or something.

**Comment by chippmann** [comment]
You mean something simpler than https://github.com/utopia-rise/godot-kotlin-3d-demo or would that suffice once #527 is fixed?

**Comment by travisfw** [comment]
godot-kotlin-3d-demo is great, so no, I guess once #527 is fixed nothing more would be necessary. It's just way more than I expected, and I was looking for something bare-bones to eliminate the possibility that godot-kotlin-3d-demo had an issue.

**Comment by CedNaru** [comment]
The 3D demo is a more "complete" project, exhaustive enough that it can cover most common uses of the module.
I guess we can just make a project that simply renders a "Hello world" text on screen.

**Comment by CedNaru** [comment]
This template project was added with the latest release:
https://github.com/utopia-rise/godot-kotlin-project-template
