### ISSUE TITLE
Issues with IntelliJ plugin 0.8.0

### ISSUE THREAD

**Issue by LukasVykuka** [utopia-rise/godot-kotlin-jvm#557]
After creating Godot project via IntelliJ plugin icon.svg is not created.

Also suspicious is that dependency on debug variant of library is created (godot-library-**debug**-0.8.0-4.2.0.jar vs godot-library-0.7.2-4.1.2.jar).
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/8152190/f05eecd5-e6f0-4266-aadf-53cc6b164918)

**Comment by piiertho** [comment]
Debug and release variant of godot-library is new with this release. In debug you have extra checks.

https://godot-kotl.in/en/0.8.0-4.2.0/user-guide/compiling-your-project/

This should not have link with svg issue.
