### ISSUE TITLE
Game Window closes itself without any error message when GDJ files are outdated

### ISSUE THREAD

**Issue by MartinHaeusler** [utopia-rise/godot-kotlin-jvm#562]
I've experienced the following several times:
- change some kotlin files which have `@RegisterClass` on them
- forget to rebuild gradle
- switch to godot editor
- launch the game
- the game window appears...
- ... and closes itself immediately again

The issue here is that we get **no error message** or any indication of what went wrong. Perhaps we could improve upon this by showing some logs?

**Comment by chippmann** [comment]
The logs should already be printed to the editor log window as well as to the system terminal (if the editor was launched through that).
I'll check what C# does here and suggest that we'll align us with them there as they have the same challanges

**Comment by MartinHaeusler** [comment]
@chippmann I've never seen this issue again ever since. Maybe it was some sort of race condition between my gradle build running in the background and the godot editor grabbing the GDJ files. But I agree, seeing some kind of message in case of a fatal error would be very useful for debugging.
