### ISSUE TITLE
Editor crashes when *.gdj files are added to Godot project root 

### ISSUE THREAD

**Issue by liza-kl** [utopia-rise/godot-kotlin-jvm#568]
Hello :) 

I'm on a MacOS Sonoma 14.3 / ARM64, using the editor from the latest release (0.8.1, but I tried this also with 0.8.0) 

- I created a Kotlin Project (with the Godot Kotlin/JVM project wizard),
- Also storing the Godot Project files in there (as proposed in the Getting Started Project Structure) 
- The Godot editor is fine until I run`./gradlew build`. Then, the `*.gdj` files are created. This is the moment the editor crashes.
When I remove the contents in the `gdj` folder in the Kotlin project, the editor is okay again and not crashing. 
- I also tried to keep the Kotlin project out of the Godot project and manually add the `*.gdj` scripts, but it crashed.

A little help would be highly appreciated!

**Comment by piiertho** [comment]
Hello ! Can you start app from a terminal by executing `Contents/MacOS/Godot` exe inside editor app to check if there is any log ?

**Comment by liza-kl** [comment]
> Hello ! Can you start app from a terminal by executing `Contents/MacOS/Godot` exe inside editor app to check if there is any log ?

Hello :) 
It worked indeed by starting it from the `Contents/MacOS/Godot`. However, it asked every time (about 12? times per startup) for permissions for the `Documents` folder. After moving the whole project to the home directory, it stopped asking and works for now (also executing the basic "Hello World" script)

**Comment by piiertho** [comment]
I think this is because your `JAVA_HOME` env variable is not defined using `launchctl`, and so is available in terminal only.  
You really should embed a JVM in your project.
On our side we should add a warn popup for this error.

**Comment by liza-kl** [comment]
After executing `launchctl setenv JAVA_HOME </path/to/jdk>` I am now able to start the Godot Engine from the Applications folder and nothing is crashing :)
