### ISSUE TITLE
message "could not create script in filesystem" on attempted "attach script" w language: Kotlin

### ISSUE THREAD

**Issue by travisfw** [utopia-rise/godot-kotlin-jvm#582]
Godot version 0.8.1-4.2.0
![Screenshot from 2024-03-06 10-36-24](https://github.com/utopia-rise/godot-kotlin-jvm/assets/655987/b4768b08-6f19-4ebf-bd03-23ab093df2fb)
![Screenshot from 2024-03-06 10-36-44](https://github.com/utopia-rise/godot-kotlin-jvm/assets/655987/291167b2-7e34-40ad-947d-7faa14df4755)

**Comment by desert-dev** [comment]
Same for me

**Comment by piiertho** [comment]
Hello !
This is currently being reworked in #579
For now please create script within IDE and attach them using drag and drop.
