### ISSUE TITLE
`usercode.a` is not added to iOS export anymore

### ISSUE THREAD

**Issue by piiertho** [utopia-rise/godot-kotlin-jvm#599]
It seems a recent modification in godot's code base broke our iOS export, see [here](https://github.com/godotengine/godot/issues/90173).  
Currently we have to manually add `usercode.a` static library to generated xcode project to overcome this limitation.

**Comment by chippmann** [comment]
@CedNaru but this will only be fixed in 4.3 no? so too early to be closed?

**Comment by CedNaru** [comment]
This is already solved with Godot 4.2.2
