### ISSUE TITLE
Idea Plugin not upgarde to 0.9.1-4.2.2

### ISSUE THREAD

**Issue by BryanSer** [utopia-rise/godot-kotlin-jvm#645]
https://plugins.jetbrains.com/plugin/16505-godot-kotlin-jvm
Current plugin version is 0.9.0-4.2.2.
If set gradle plugin version to 0.9.1-4.2.2 will get a warning like this:
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/26378249/997cf578-f354-40da-900d-1dd4f778ad7f)

**Comment by CedNaru** [comment]
We just checked, the new plugin version was published by our CI but refused by Jetbrains. It uses API call that are now depecrated. We have to rework parts of it.

**Comment by jsbeckr** [comment]
@BryanSer if you want to be sneaky, you can download the plugin from [a recent pipeline run](https://github.com/utopia-rise/godot-kotlin-jvm/actions/runs/9540347198/artifacts/1606751226) and install it yourself in IntelliJ. :)

**Comment by chippmann** [comment]
Fixed by: https://github.com/utopia-rise/godot-kotlin-jvm/pull/654
Should be regularly release in the next release
