### ISSUE TITLE
Why the member method without RegisterFunction annotation will leak when game exit?

### ISSUE THREAD

**Issue by BryanSer** [utopia-rise/godot-kotlin-jvm#650]
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/26378249/3b46f6fe-ea5e-4f53-897c-d2667ca15bf2)
 When i remove the @RegisterFunction annotation. After game exit, will show jvm leak dialog:
 
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/26378249/f04e88bb-668c-468d-9af8-2c23702f033e)

playerBackpack is a node.

**Comment by piiertho** [comment]
Hello ! Since playerBackpack is a Node, you have to free it manually.
Do you free it ?

**Comment by BryanSer** [comment]
> Hello ! Since playerBackpack is a Node, you have to free it manually. Do you free it ?

Thanks for you reply.
I have not free playerBackpack. playerBackpack is get by getNodeAs(), i think it will be free by parent.
Why doesn't the leak warning pop up after I added the @RegisterFunction annotation?

**Comment by CedNaru** [comment]
How do you call this method ?
It should be totally fine (or at least I don't see any reason for a leak) if you call it only from another Kotlin code. But do you maybe try to use it from GDSCript or even as the callable for a signal ? In such case, if you don't register it, the method call will fail, trigger an error and probably prevent other code to be executed (code that might be freeing some stuff).

Do you have any logs to share that would show some warning/error ? Or at least the list of leaked instances, that one should be pinted do your console.

**Comment by BryanSer** [comment]
> How do you call this method ? It should be totally fine (or at least I don't see any reason for a leak) if you call it only from another Kotlin code. But do you maybe try to use it from GDSCript or even as the callable for a signal ? In such case, if you don't register it, the method call will fail, trigger an error and probably prevent other code to be executed (code that might be freeing some stuff).
> 
> Do you have any logs to share that would show some warning/error ? Or at least the list of leaked instances, that one should be pinted do your console.

I called it from _input method. 
I retested it, and it's strange that this issue doesn't exist on another device. The purpose of my issue is to understand the essential reasons behind this behavior, which currently seems to be caused by a specific operating environment.
Thanks for your reply, but we can stop paying attention to this problem until I can encounter it stably.
