### ISSUE TITLE
Editor won't open because it doesn't detect OpenGL support properly

### ISSUE THREAD

**Issue by sharkdude6789** [utopia-rise/godot-kotlin-jvm#735]
My card supports OpenGL 4.4, and I have had it hardware accelerate everything properly. And yet, when I start the jvm godot editor, it throws this error at me.

![image](https://github.com/user-attachments/assets/a82e0ad5-2455-4836-9587-1e03503aeb3b)

PC Specs:
OS: Windows 10 Pro 22H2 build 19045.5011
CPU: Intel Core i5-4670S
GPU: AMD Radeon HD 7600A

(It is a slightly upgraded HP EliteOne 800 G1 Touch All-In-One :3)

I might try restarting or trying on a different PC, but this is the only one I have available to me right now.

**Comment by sharkdude6789** [comment]
Update: restarting didn't do anything

**Comment by sharkdude6789** [comment]
Closing, sorry for bothering. When using an older version, it simply doesn't have this check, and so runs with visual glitches everywhere.

**Comment by chippmann** [comment]
In any case that would be a problem from godot itself and not our project. We're just a language binding and have no influence on graphics. So if a issue like this arises you would need to test that with vanilla godot and if it also exists there, report it to the godot project.

**Comment by sharkdude6789** [comment]
issue closed, but the issue is not godot related as godot runs fine
