### ISSUE TITLE
`RandomNumberGenerator`leaked upon use of `GD` object

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin-jvm#86]
As we store a `RandomNumberGenerator` inside the `GD` object, it is in fact "leaked" and will trigger the leaked exception in our GC when closing the application.
In fact the "leakage" is not a problem as the application closes anyways but we need to either not leak it or fix the error message about it.

Leaking object:
```kotlin
object GD : GDMath, GDCore, GDRandom, GDPrint {
    override val rng = RandomNumberGenerator() //<- this one leaks if this object is used

    //...
}
```

**Comment by CedNaru** [comment]
I suggest to add an internal interface that will register the instance in a new list in the garbage collector and will require you to implement a "free" method.
When the JVM is closing, we will iterate this list and call the "free" method before cleaning up the GC.

**Comment by chippmann** [comment]
> I suggest to add an internal interface that will register the instance in a new list in the garbage collector and will require you to implement a "free" method.
> When the JVM is closing, we will iterate this list and call the "free" method before cleaning up the GC.

This would require us to move the `GD` object and it's interfaces to `godot-runtime` as the GC is in `godot-runtime` and the `GD` object is in `godot-library`. Otherwise the interface cannot be internal.
I'm generally fine with this as our core types are also in `godot-runtime`. But if we do this i think we have to think again about the naming and the purposes of `godot-runtime` and `godot-library` as the `runtime` does not include just runtime things anymore like it used to.
The idea of keeping them separate was to be able to more easily reimplement the `runtime` for `iOS` and `Android` IIRC, but @raniejade knows for sure.
I any case at the current state the line we draw between `library` and `runtime` is not clear and it becomes even unclearer IMO if we move those singletons to the `runtime`.
